(()=>{const frame=document.getElementById('prototype');frame.addEventListener('load',()=>{const d=frame.contentDocument;if(!d)return;
const style=d.createElement('style');style.textContent=`
/* Home: denser dashboard hierarchy */
#home .welcome{padding:2px 2px 9px!important}#home .welcome h1{font-size:15px!important;line-height:1.2!important;letter-spacing:0!important;font-weight:700!important;color:#cfcfcf!important;margin:0!important}#home .welcome p{display:none!important}#home .hero{padding:0 16px 15px!important;margin-bottom:10px!important}#home .hero .day{padding:8px 14px!important;margin-left:-16px!important;margin-bottom:18px!important;font-size:13px!important}#home .hero h1{font-size:25px!important;line-height:1.04!important}#home .hero p{font-size:13px!important;line-height:1.4!important;margin-top:15px!important}#home .hero .btn{margin-top:15px!important;padding:8px 14px!important;font-size:12px!important}#home .reward{padding:0 16px 16px!important;margin-bottom:13px!important}#home .reward .ribbon{padding:8px 13px!important;margin-left:-16px!important;margin-bottom:17px!important;font-size:12px!important}#home .reward h2{font-size:20px!important}#home .reward p{font-size:13px!important;margin-top:12px!important}#home .reward .btn{margin-top:14px!important;padding:8px 14px!important;font-size:12px!important}#home .section{font-size:15px!important;margin-top:2px!important}
/* My Day: let position communicate routine state */
#day .appt{min-height:82px!important;padding-top:10px!important;padding-bottom:10px!important}#day .appt .status{display:none!important}#day .appt.live .status,#day .appt.new .status,#day .appt.cancel .status{display:block!important}#day .appt.done{opacity:.42!important}#day .dayModule{padding-top:12px!important;padding-bottom:12px!important;margin-bottom:9px!important}#day .dayModule h1{font-size:20px!important}#day .dayModule .muted{font-size:10px!important}#day .dayBrief{padding-top:9px!important;padding-bottom:10px!important}.dayCount{margin-bottom:5px!important}.dayEarned{font-size:22px!important}.dayTrack{margin-top:9px!important}
/* Open slot: meaning first, duration second */
#day .appt.open{grid-template-columns:1fr auto!important}#day .appt.open>div:not(.time):not(.status){grid-column:1!important;grid-row:1!important}#day .appt.open .name{font-size:16px!important;color:#aaa!important}#day .appt.open .svc{display:none!important}#day .appt.open .time{grid-column:2!important;grid-row:1!important;justify-self:end!important;color:#686868!important;font-size:12px!important;font-weight:700!important;text-transform:lowercase!important}#day .appt.open .status{display:none!important}
`;d.head.appendChild(style);
/* Home copy */const greeting=d.querySelector('#home .welcome h1');if(greeting)greeting.textContent='Good morning, Mervis';const welcomeSub=d.querySelector('#home .welcome p');if(welcomeSub)welcomeSub.remove();
/* Remove routine status text, preserve exceptional states */d.querySelectorAll('#day .appt').forEach(card=>{const status=card.querySelector('.status');if(!status)return;const value=status.textContent.trim().toUpperCase();if(value==='UPCOMING'||value==='COMPLETE')status.remove();});
/* Open spots: Open Spot first, duration at right */d.querySelectorAll('#day .appt.open').forEach(card=>{const name=card.querySelector('.name');const time=card.querySelector('.time');const svc=card.querySelector('.svc');if(name)name.textContent='Open Spot';if(svc)svc.remove();if(time){const raw=(time.textContent||'').trim();const duration=raw.match(/\d+\s*[mM]/)?.[0]||'45m';time.textContent=duration.toLowerCase().replace(/\s+/g,'');}});
});})();