const BUSINESSES=[
 {name:'Blissful Lashes',suite:'C',summary:'Lash studio',tone:'linear-gradient(135deg,#6f5557,#bf8e91 52%,#e1c7bd)'},
 {name:'Pacific Skin',suite:'D',summary:'Skin care & esthetics',tone:'linear-gradient(135deg,#758176,#9fae9c 48%,#d7d4c5)'},
 {name:'Bona MUA',suite:'E',summary:'Makeup artistry',tone:'linear-gradient(135deg,#6b625c,#b99d87 55%,#e2d2bf)'},
 {name:'Freckled Ink',suite:'F',summary:'Independent beauty studio',tone:'linear-gradient(135deg,#34393a,#6e7774 50%,#a7a098)'},
 {name:'Ruslana Aesthetics',suite:'G',summary:'Aesthetics studio',tone:'linear-gradient(135deg,#726960,#9e8e7e 50%,#d2c2ae)'},
 {name:'MB Nail Designs',suite:'H',summary:'Nail design studio',tone:'linear-gradient(135deg,#6b5a65,#a78395 52%,#d2b6bf)'}
];
const COPY={
 en:{heroEyebrow:'Bothell, Washington',heroHeadline:'Space to build something of your own.',heroBody:'Six private suites for independent businesses, brought together under one roof.',businessEyebrow:'Inside Bothell Suites',businessHeadline:'Independent businesses. All under one roof.',businessDeck:'Meet the professionals who have made each suite their own.',leasingHeadline:'Make it Yours.',leased:'Fully leased. For now.',leasedBody:'All six suites are currently occupied. Join the interest list and be the first to hear when a space opens.',join:'Join the interest list',location:'Come find us.',book:'Book',explore:'Explore',visit:'Visit website',close:'Close',businesses:'Businesses',make:'Make it Yours',find:'Find Us'},
 es:{heroEyebrow:'Bothell, Washington',heroHeadline:'Un espacio para construir algo propio.',heroBody:'Seis suites privadas para negocios independientes, reunidas bajo un mismo techo.',businessEyebrow:'Dentro de Bothell Suites',businessHeadline:'Negocios independientes. Bajo un mismo techo.',businessDeck:'Conoce a los profesionales que han hecho suyo cada espacio.',leasingHeadline:'Hazlo tuyo.',leased:'Completamente alquilado. Por ahora.',leasedBody:'Las seis suites están ocupadas. Únete a la lista de interés para saber primero cuando se abra un espacio.',join:'Únete a la lista',location:'Encuéntranos.',book:'Reservar',explore:'Explorar',visit:'Visitar sitio web',close:'Cerrar',businesses:'Negocios',make:'Hazlo tuyo',find:'Ubicación'}
};
let lang=localStorage.getItem('bs-lang')||'en'; let edit=false;
const q=(s,p=document)=>p.querySelector(s), qa=(s,p=document)=>[...p.querySelectorAll(s)];
function applyCopy(){const c=COPY[lang];qa('[data-copy]').forEach(el=>{const k=el.dataset.copy;if(c[k]&&!el.dataset.userEdited)el.textContent=c[k]});q('#langBtn').textContent=lang==='en'?'EN / ES':'ES / EN';document.documentElement.lang=lang}
function photoMarkup(id,bg){return `<div class="photo-controls" hidden><label>Change photo<input type="file" accept="image/*" data-upload="${id}"></label><select aria-label="Photo position" data-position="${id}"><option value="left center">Left</option><option value="center center" selected>Center</option><option value="right center">Right</option></select></div>`}
function renderBusinesses(){const wrap=q('#businessScroller');wrap.innerHTML=BUSINESSES.map((b,i)=>`<article class="business-card" data-business="${i}"><div class="photo card-photo" id="photo-business-${i}" data-placeholder="Add ${b.name} photography" style="background:${b.tone};background-size:cover;background-position:center">${photoMarkup('business-'+i,b.tone)}</div><div class="card-meta"><div><div class="business-name">${b.name}</div><div class="business-summary">Suite ${b.suite} · ${b.summary}</div></div><div class="card-actions"><button class="btn primary" data-copy="book">Book</button><button class="btn" data-explore="${i}" data-copy="explore">Explore</button></div></div></article>`).join('');applySavedPhotos();bindPhotoControls();applyCopy()}
function openBusiness(i){const b=BUSINESSES[i],d=q('#businessDialog');q('#dialogName').textContent=b.name;q('#dialogMeta').textContent=`Suite ${b.suite} · ${b.summary}`;q('#dialogBody').textContent=`${b.name} is one of six independent businesses at Bothell Suites. This lightweight profile keeps the shared experience focused, while booking and detailed services can live on the business’s own website.`;const src=q('#photo-business-'+i);const dst=q('#dialogPhoto');dst.style.background=src.style.background;dst.style.backgroundImage=src.style.backgroundImage;dst.style.backgroundPosition=src.style.backgroundPosition;dst.style.backgroundSize='cover';dst.dataset.hasImage=src.dataset.hasImage||'false';d.showModal()}
function setEdit(v){edit=v;qa('.editable').forEach(el=>el.contentEditable=v?'true':'false');qa('.photo-controls').forEach(el=>el.hidden=!v);q('#editbar').hidden=!v;q('#menu').hidden=true}
function saveText(){qa('.editable').forEach(el=>{localStorage.setItem('bs-text-'+el.id,el.innerHTML);el.dataset.userEdited='true'});setEdit(false)}
function restoreText(){qa('.editable').forEach(el=>{const v=localStorage.getItem('bs-text-'+el.id);if(v){el.innerHTML=v;el.dataset.userEdited='true'}})}
function bindPhotoControls(){qa('[data-upload]').forEach(inp=>inp.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const id=e.target.dataset.upload;const r=new FileReader();r.onload=()=>{localStorage.setItem('bs-img-'+id,r.result);applySavedPhotos()};r.readAsDataURL(f)}));qa('[data-position]').forEach(sel=>sel.addEventListener('change',e=>{localStorage.setItem('bs-pos-'+e.target.dataset.position,e.target.value);applySavedPhotos()}))}
function applySavedPhotos(){['hero','leasing',...BUSINESSES.map((_,i)=>'business-'+i)].forEach(id=>{const el=q('#photo-'+id);if(!el)return;const img=localStorage.getItem('bs-img-'+id),pos=localStorage.getItem('bs-pos-'+id)||'center center';if(img){el.style.backgroundImage=`url(${img})`;el.style.backgroundSize='cover';el.dataset.hasImage='true'}el.style.backgroundPosition=pos;const sel=q(`[data-position="${id}"]`);if(sel)sel.value=pos})}
function init(){renderBusinesses();restoreText();applyCopy();bindPhotoControls();applySavedPhotos();q('#menuBtn').onclick=()=>q('#menu').hidden=!q('#menu').hidden;q('#themeBtn').onclick=()=>{const h=document.documentElement;h.dataset.theme=h.dataset.theme==='dark'?'light':'dark';localStorage.setItem('bs-theme',h.dataset.theme)};q('#langBtn').onclick=()=>{lang=lang==='en'?'es':'en';localStorage.setItem('bs-lang',lang);applyCopy()};q('#editBtn').onclick=()=>setEdit(true);q('#cancelEdit').onclick=()=>setEdit(false);q('#saveEdit').onclick=saveText;q('#resetEdit').onclick=()=>{if(confirm('Reset demo edits and uploaded images?')){Object.keys(localStorage).filter(k=>k.startsWith('bs-text-')||k.startsWith('bs-img-')||k.startsWith('bs-pos-')).forEach(k=>localStorage.removeItem(k));location.reload()}};document.addEventListener('click',e=>{const x=e.target.closest('[data-explore]');if(x)openBusiness(+x.dataset.explore)});q('#closeDialog').onclick=()=>q('#businessDialog').close();q('#businessDialog').addEventListener('click',e=>{if(e.target===q('#businessDialog'))q('#businessDialog').close()});q('#interestBtn').onclick=()=>alert('Demo: open a short interest form — name, contact, business type, desired timing.');qa('[data-copy="book"]').forEach(b=>b.onclick=()=>alert('Demo: this would open the tenant’s booking link.'))}
const savedTheme=localStorage.getItem('bs-theme');if(savedTheme)document.documentElement.dataset.theme=savedTheme;init();