const BUSINESSES=[
{name:'Blissful Lashes',suite:'C',summary:'Lash studio',image:'blissful-lashes/blissful-lashes-01.jpg',page:'blissful-lashes/'},
{name:'Pacific Skin',suite:'D',summary:'Skin care & esthetics',image:'pacific-skin/pacfiic-skin-01.png',page:'pacific-skin/'},
{name:'Bona MUA',suite:'E',summary:'Makeup artistry',image:'bonmua/bonmua-01.png',page:'bonmua/'},
{name:'Freckled Ink',suite:'F',summary:'Beauty & permanent cosmetics',image:'frackled/freckled-01.png',page:'frackled/'},
{name:'Ruslana Aesthetics',suite:'G',summary:'Aesthetics studio',image:'rusiana/rusiana-01.png',page:'rusiana/'},
{name:'MB Nail Designs',suite:'H',summary:'Nail design studio',image:'mb-nail/MB-nail01.png',page:'mb-nail/'}];
let edit=false,available=false;const q=(s,p=document)=>p.querySelector(s),qa=(s,p=document)=>[...p.querySelectorAll(s)];
function card(b,i){return `<article class="business-card hero-card"><a class="card-link" href="${b.page}" aria-label="View ${b.name}"><div class="photo card-photo" id="photo-business-${i}" style="background-image:url('${b.image}')"></div><div class="card-overlay"><div><div class="business-name">${b.name}</div><div class="business-summary">${b.summary} · Suite ${b.suite}</div></div><span class="round-arrow">↗</span></div></a><a class="card-book" href="${b.page}#book">Book</a></article>`}
function renderBusinesses(){let html=BUSINESSES.map(card).join('');if(available)html+=`<article class="business-card hero-card vacancy-card"><a class="card-link" href="#leasing"><div class="vacancy-art"><span>Suite available</span><strong>This could<br>be you.</strong><em>Make Bothell Suites your own →</em></div></a></article>`;q('#businessScroller').innerHTML=html}
function setState(v){available=v;renderBusinesses();q('#stateBtn').textContent=v?'Suite available':'Fully leased';q('#leaseStatus').textContent=v?'A suite is available.':'Fully leased. For now.';q('#leasingBody').textContent=v?'A private suite is ready for its next independent business. See the space and tell us what you want to build here.':'All six suites are currently occupied. Join the waitlist and be first to hear when a space opens.';q('#interestBtn').textContent=v?'Inquire about the suite':'Join waitlist';q('#availabilityFact').textContent=v?'Suite available':'Fully leased'}
function setEdit(v){edit=v;qa('.editable').forEach(el=>el.contentEditable=v?'true':'false');qa('.photo-controls').forEach(el=>el.hidden=!v);q('#editbar').hidden=!v;q('#menu').hidden=true}
function bindPhotos(){qa('[data-upload]').forEach(inp=>inp.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const el=q('#photo-'+e.target.dataset.upload);el.style.backgroundImage=`url(${r.result})`};r.readAsDataURL(f)});qa('[data-position]').forEach(sel=>sel.onchange=e=>q('#photo-'+e.target.dataset.position).style.backgroundPosition=e.target.value)}
function init(){renderBusinesses();bindPhotos();q('#stateBtn').onclick=()=>setState(!available);q('#menuBtn').onclick=()=>q('#menu').hidden=!q('#menu').hidden;q('#themeBtn').onclick=()=>document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';q('#langBtn').onclick=()=>alert('Spanish content demo: the production version will switch navigation, leasing and shared Bothell Suites copy while preserving tenant brand names.');q('#editBtn').onclick=()=>setEdit(true);q('#cancelEdit').onclick=()=>setEdit(false);q('#saveEdit').onclick=()=>setEdit(false);q('#resetEdit').onclick=()=>location.reload();q('#interestBtn').onclick=()=>alert(available?'Demo: suite inquiry — name, contact, business type, desired timing.':'Demo: waitlist — name, contact, business type.');}init();